import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'package:teamzone_app/src/features/attendance_export/export_models.dart';
import 'package:teamzone_app/src/features/attendance_export/export_services.dart';
import 'package:teamzone_app/src/features/attendance_export/laget_se/laget_se_adapter.dart';

/// Hands generated bytes to the user. Returns false when the user cancelled.
abstract interface class ExportFileSaver {
  Future<bool> save({required String fileName, required Uint8List bytes});
}

/// Uses the app's existing file_picker: a browser download on web and the
/// system "save as" sheet on Android/iOS. The bytes go straight to the
/// chosen destination — no temporary copy is written by Teamzone.
class FilePickerExportFileSaver implements ExportFileSaver {
  const FilePickerExportFileSaver();
  @override
  Future<bool> save({
    required String fileName,
    required Uint8List bytes,
  }) async {
    final path = await FilePicker.platform.saveFile(
      fileName: fileName,
      bytes: bytes,
      type: FileType.custom,
      allowedExtensions: const ['json'],
    );
    // The web download has no path to report.
    return kIsWeb || path != null;
  }
}

String lagetSeFileName(String teamzoneEventId) =>
    'laget_se_$teamzoneEventId.json';

enum ExportOutcomeKind {
  /// Validation errors; no file was created.
  blocked,

  /// The user closed the save dialog; nothing was created or logged.
  cancelled,

  /// The file could not be saved; logged as failed.
  failed,

  /// The file was saved and logged as "Exportfil skapad".
  fileCreated,

  /// The file was saved but the log entry could not be written.
  fileCreatedNotLogged,
}

class ExportOutcome {
  const ExportOutcome(this.kind, this.result, {this.fileName});
  final ExportOutcomeKind kind;
  final LagetSeExportResult result;
  final String? fileName;
}

class AttendanceExportRunner {
  const AttendanceExportRunner({required this.services, required this.saver});
  final AttendanceExportServices services;
  final ExportFileSaver saver;

  Future<ExportOutcome> exportToLagetSe({
    required AttendanceExportBasis basis,
    required ExportContext context,
    Set<String> excludedPersonIds = const {},
    required bool confirmedComplete,
  }) async {
    final result = generateLagetSeExport(
      basis: basis,
      context: context,
      excludedPersonIds: excludedPersonIds,
      confirmedComplete: confirmedComplete,
    );
    final file = result.file;
    if (file == null) return ExportOutcome(ExportOutcomeKind.blocked, result);
    final fileName = lagetSeFileName(basis.eventId);
    final bool saved;
    try {
      saved = await saver.save(fileName: fileName, bytes: file.bytes());
    } catch (_) {
      try {
        await services.recordExport(
          eventId: basis.eventId,
          teamId: basis.teamId,
          provider: lagetSeProvider,
          state: ExportState.failed,
          externalActivityId: file.activityId,
          summary: result.summary.toJson(),
          confirmedComplete: confirmedComplete,
          errorCode: 'file_save_failed',
        );
      } catch (_) {
        // The failure is still shown; the log entry is best effort.
      }
      return ExportOutcome(ExportOutcomeKind.failed, result);
    }
    if (!saved) return ExportOutcome(ExportOutcomeKind.cancelled, result);
    try {
      await services.recordExport(
        eventId: basis.eventId,
        teamId: basis.teamId,
        provider: lagetSeProvider,
        state: ExportState.fileCreated,
        externalActivityId: file.activityId,
        summary: result.summary.toJson(),
        confirmedComplete: confirmedComplete,
        payloadSha256: file.sha256Hex(),
      );
    } catch (_) {
      return ExportOutcome(
        ExportOutcomeKind.fileCreatedNotLogged,
        result,
        fileName: fileName,
      );
    }
    return ExportOutcome(
      ExportOutcomeKind.fileCreated,
      result,
      fileName: fileName,
    );
  }
}
