create policy callup_response_tokens_no_direct_read on core.callup_response_tokens for select to authenticated using(false);
create index squad_revisions_event_club_idx on core.squad_revisions(event_id,club_id);
create index squad_revisions_created_by_idx on core.squad_revisions(created_by);
create index squad_members_revision_club_idx on core.squad_members(squad_revision_id,club_id);
create index squad_members_event_club_idx on core.squad_members(event_id,club_id);
create index squad_members_person_club_idx on core.squad_members(club_person_id,club_id);
create index squad_members_eligibility_club_idx on core.squad_members(eligibility_id,club_id) where eligibility_id is not null;
create index squad_members_created_by_idx on core.squad_members(created_by);
create index callups_event_club_idx on core.callups(event_id,club_id);
create index callups_squad_club_idx on core.callups(squad_revision_id,club_id);
create index callups_person_club_idx on core.callups(club_person_id,club_id);
create index callups_created_by_idx on core.callups(created_by);
create index response_tokens_callup_club_idx on core.callup_response_tokens(callup_id,club_id);
create index callup_responses_callup_club_idx on core.callup_responses(callup_id,club_id);
create index callup_responses_actor_idx on core.callup_responses(actor_profile_id);
create index callup_responses_acting_as_club_idx on core.callup_responses(acting_as_person_id,club_id) where acting_as_person_id is not null;
create index attendance_event_club_idx on core.attendance_facts(event_id,club_id);
create index attendance_person_club_idx on core.attendance_facts(club_person_id,club_id);
create index attendance_recorded_by_idx on core.attendance_facts(recorded_by);
create index attendance_revisions_attendance_club_idx on audit.attendance_revisions(attendance_id,club_id);
create index attendance_revisions_actor_idx on audit.attendance_revisions(actor_profile_id);
create index command_events_acting_as_club_idx on audit.command_events(acting_as_person_id,club_id) where acting_as_person_id is not null;
create index notification_outbox_club_idx on internal.notification_outbox(club_id);
create index notification_outbox_person_club_idx on internal.notification_outbox(recipient_person_id,club_id);
create index delivery_attempts_endpoint_idx on internal.delivery_attempts(endpoint_id) where endpoint_id is not null;
insert into internal.migration_provenance(migration_name,source_kind,source_reference)values('20260808080726_s04_advisor_hardening','greenfield',null);
